spring.application.name=knowlegde-management

springdoc.api-docs.enabled=true

# Common logging
logging.level.com.example.knowledge_management=INFO
logging.level.org.springframework=WARN

## Actuator
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always